# This is a basic workflow to help you get started with Actions

name: Build Adguard List

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
    - main
    - release/*
  schedule:
        - cron: '30 17 * * 0-6'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install HostlistCompiler
        run: npm i -g @adguard/hostlist-compiler
     # Runs a set of commands using the runners shell
      - name: Build Adguard list
        working-directory: .\Adguard-Filter
        run: hostlist-compiler -c configuration5.json -o Adguardstylepc.txt
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: generate domain
        working-directory: .\DNScrypt-Filter
        run: py generate-domains-blocklist.py -o blocked-names.txt
      - name: upload
        run: |
          git config --global user.name 'unknown4849'
          git config --global user.email '74445408+unknown4849@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add DNScrypt-Filter/blocked-names.txt
          git add Adguard-Filter/Adguardstylepc.txt
          git commit -m "update"
          git push
  
  workflow-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2.1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
