# This is a basic workflow to help you get started with Actions

name: Build dnscrypt List

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
   schedule:
          - cron: '00 17 * * 0-6'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: .\DNScrypt-Filter
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - run: py generate-domains-blocklist.py -o blocked-names.txt
    
    - name: upload
      run: |
          git config --global user.name 'unknown4849'
          git config --global user.email '74445408+unknown4849@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add blocked-names.txt
          git commit -m "update"
          git push
